environment:
  nodejs_version: "1"

  matrix:
    - platform: x64
      openssl_pkg: "Win64OpenSSL-1_0_2a.exe"
      openssl_url: "http://slproweb.com/download/Win64OpenSSL-1_0_2a.exe"

    - platform: x86
      openssl_pkg: "Win32OpenSSL-1_0_2a.exe"
      openssl_url: "http://slproweb.com/download/Win32OpenSSL-1_0_2a.exe"

# Runs after repo cloning.
install:
  - ps: Start-FileDownload $env:openssl_url
  - ps: Start-Process $env:openssl_pkg -ArgumentList "/verysilent /suppressmsgboxes" -Wait

  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version

# Run custom scripts instead of automatic MSBuild
build_script:
  - cd electron\hadron && cd
  - npm install --msvs_version=2013

test_script:
  - npm test

artifacts:
  - path: electron\hadron\build\Release\hadron.node
